# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - development
    exclude:
    - releases/old*
    - feature/*-working
  paths:
    include:
    - Oversight/*
    exclude:
    - Plugin/*
    - WebResources/*

pool:
  vmImage:  'vs2017-win2016'

steps:

- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true

- task: PowerPlatformImportSolution@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'ROM QA'
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\$(TCSolutionName)_Base_managed.zip'
    AsyncOperation: true
    MaxAsyncWaitTime: '240'
    OverwriteUnmanagedCustomizations: true
    SkipProductUpdateDependencies: true

- task: PowerPlatformImportSolution@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'ROM QA'
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName)_Base_managed.zip'
    AsyncOperation: true
    MaxAsyncWaitTime: '240'
    OverwriteUnmanagedCustomizations: true
    SkipProductUpdateDependencies: true

- task: PowerPlatformImportSolution@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'ROM QA'
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName)_Conf_managed.zip'
    AsyncOperation: true
    MaxAsyncWaitTime: '240'
    OverwriteUnmanagedCustomizations: true
    SkipProductUpdateDependencies: true

- task: PowerPlatformImportSolution@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'ROM QA'
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName)_Proc_managed.zip'
    AsyncOperation: true
    MaxAsyncWaitTime: '240'
    OverwriteUnmanagedCustomizations: true
    SkipProductUpdateDependencies: true

- task: PowerPlatformImportSolution@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'ROM QA'
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\$(TCSolutionName)_Code_managed.zip'
    AsyncOperation: true
    MaxAsyncWaitTime: '240'
    OverwriteUnmanagedCustomizations: true
    SkipProductUpdateDependencies: true
