parameters:
  - name: StageName
    type: string
  - name: VersionNumber
    type: string
  - name: dependsOn
    type: object
    default: []
    
stages:
- stage: ${{Parameters.StageName}}
  dependsOn:
  - ${{ each stage in parameters.dependsOn }}:
    - ${{ stage }}
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: ${{Parameters.StageName}}
    steps:
      - task: PowerShell@2
        displayName: Set the name of the build (i.e. the Build.BuildNumber)
        inputs:
          targetType: 'inline'
          script: |
            [string] $buildName = "$(VersionNumber)"
            Write-Host "Setting the name of the build to '$buildName'."
            Write-Host "##vso[build.updatebuildnumber]$buildName"