parameters:
  ConnectionString: ''
  SolutionName: 'TC_GlobalCore'

stages:
- stage: DeployManagedSolutionToDev
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: CreatePatchOnDev
      pool: 'windows-latest'
      steps:
      - task: MSCRMToolInstaller@12
        displayName: Power DevOps Tool Installer
      - task: MSCRMPublishCustomizations@12
        displayName: Publish Customizations
        inputs:
          crmConnectionString: '${{ConnectionString}}'
          crmConnectionTimeout: '3600'
      - task: MSCRMCreatePatch@12
        displayName: 'Create Patch: ${{SolutionName}}'
        inputs:
          crmConnectionString: '${{ConnectionString}}'
          uniqueName: '${{SolutionName}}'
          crmConnectionTimeout: '21600'