parameters:
  - name: SolutionName
    type: string
    value: 'TC_GlobalCore'
  - name: ConnectionString
    type: string
    value: ''

stages:
- stage: CreatePatchOnDev
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: CreatePatchOnDev
    steps:
    - task: MSCRMToolInstaller@12
      displayName: Power DevOps Tool Installer
    - task: MSCRMPublishCustomizations@12
      displayName: Publish Customizations
      inputs:
        crmConnectionString: '${{Parameters.ConnectionString}}'
        crmConnectionTimeout: '3600'
    - task: MSCRMCreatePatch@12
      displayName: 'Create Patch: ${{Parameters.SolutionName}}'
      inputs:
        crmConnectionString: '${{Parameters.ConnectionString}}'
        uniqueName: '${{Parameters.SolutionName}}'
        crmConnectionTimeout: '21600'