trigger:
- none

pool:
  vmImage: windows-latest

steps:
- task: MSCRMToolInstaller@12
  inputs:
    nugetFeed: 'official'
    psFeed: 'official'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module -Name Microsoft.Xrm.Tooling.ConfigurationMigration -force
      
      $basepath = "$(Build.SourcesDirectory)"
      $schemaFile = "$basepath/ConfigurationMigration/schema/CostRecoveryAttributes.xml"
      $dataFile = "$(Agent.TempDirectory)/CostRecoveryAttributes.zip"
      $crmConnection = "$(ConnectionStringDev)"
      $logWriteDirectory = "$basepath\logs\export\"
      
      If(!(test-path "$basepath/ConfigurationMigration/logs/export"))
      {
          Write-Host "$basepath/ConfigurationMigration/logs/export folder does not exists."
          New-Item -ItemType Directory -Force -Path "$basepath/ConfigurationMigration/logs/export"
          Write-Host "$basepath/ConfigurationMigration/logs/export folder created."
      }   
      
      Export-CrmDataFile -SchemaFile $schemaFile -DataFile $dataFile -CrmConnection $crmConnection -Verbose -EmitLogToConsole -LogWriteDirectory $logWriteDirectory

# - task: MSCRMExportCMData@12
#   continueOnError: true
#   inputs:
#     crmConnectionString: '$(ConnectionStringDev)'
#     schemaFile: '$(Build.SourcesDirectory)/ConfigurationMigration/schema/ReferenceDataMigration-CostRecoveryAttributes.xml'
#     #dataFile: $(Build.SourcesDirectory)/ConfigurationMigration/data/ReferenceDataMigration-CostRecoveryAttributes.zip'
#     crmConnectionTimeout: '999'
#     logsDirectory: '$(Build.SourcesDirectory)/ConfigurationMigration/Logs/Export'
# - task: MSCRMExtractCMData@12
#   continueOnError: true
#   inputs:
#     dataFile: '../../../ConfigurationMigration/data/ReferenceDataMigration-CostRecoveryAttributes.zip'
#     extractFolder: '../../../ConfigurationMigration/data/unpacked'
#     sortExtractedData: true
#     splitExtractedData: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd $(Build.SourcesDirectory)/ConfigurationMigration/Logs/Export
      cat *
