trigger:
- none

pool:
  vmImage: windows-latest

steps:
- task: MSCRMToolInstaller@12
  inputs:
    nugetFeed: 'official'
    psFeed: 'official'
- task: MSCRMExportCMData@12
  inputs:
    crmConnectionString: '$(ConnectionStringDev)'
    schemaFile: '../../../ConfigurationMigration/schema/ReferenceDataMigration-CostRecoveryAttributes.xml'
    dataFile: '../../../ConfigurationMigration/data/ReferenceDataMigration-CostRecoveryAttributes.zip'
    crmConnectionTimeout: '999'
    logsDirectory: '$(Build.SourcesDirectory)/ConfigurationMigration/Logs/Export'
- task: MSCRMExtractCMData@12
  inputs:
    dataFile: '../../../ConfigurationMigration/data/ReferenceDataMigration-CostRecoveryAttributes.zip'
    extractFolder: '../../../ConfigurationMigration/data/unpacked'
    sortExtractedData: true
    splitExtractedData: true
- script: |
    ls
  displayName: 'Run a multi-line script'
