trigger: none
pr: none

variables:
  - name: PowerPlatformSPN_Dev
    value: 'ROM DEV TDG'
  - name: PowerPlatformSPN_QA
    value: 'ROM QA TDG'
  - name: PowerPlatformSPN_COREQA
    value: 'CORE QA TDG'
  - name: PowerPlatformSPN_ACC
    value: 'ROM ACC TDG'
  - name: PowerPlatformSPN_ACCDATA
    value: 'ROM ACC TDG DATA'
  - name: PowerPlatformSPN_PREPROD
    value: 'ROM PREPROD TDG'
  - name: PowerPlatformSPN_PROD
    value: 'ROM PROD TDG'
  - name: SolutionName
    value: 'TC_GlobalCore'

name: #Set Dynamically in Pipeline

stages:

#get the current solution version from dynamics
#version stored into environment variable ${env:SOLUTIONVERSION}
- template: templates/stage/GetLatestSchemaPatchVersion.yml  # Template reference
  parameters:
    StageName: 'GetSchemaPatch'
    SolutionName: $(SolutionName)
    ConnectionString: $(ConnectionStringDev)
    PowerPlatformSPN: $(PowerPlatformSPN_Dev)
#deploy the patch to COREQA
- template: templates/stage/DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(Build.BuildNumber)
    PowerPlatformSPN: $(PowerPlatformSPN_COREQA)
    Environment: 'COREQA-TDG'
    StageName: 'DeployManagedSolutionToCOREQA'
    dependsOn: 
    - 'GetSchemaPatch'

#deploy the patch to QA
# - template: templates/stage/DeploySolution.yml  # Template reference
#   parameters:
#     SolutionName: variables['LatestPatchName']
#     PowerPlatformSPN: $(PowerPlatformSPN_QA)
#     PowerPlatformSPN_Dev: $(PowerPlatformSPN_Dev) #used to update solution version after successful deployment to QA
#     Environment: 'QA-TDG'
#     StageName: 'DeployManagedSolutionToQA'
#     dependsOn: 
#     - 'BuildAndPublishArtifacts'

##ACC
#- template: templates/DeploySolution.yml  # Template reference
#  parameters:
#    SolutionName: $(SolutionName)
#    PowerPlatformSPN: $(PowerPlatformSPN_ACC)
#    Environment: 'ACC-TDG'
#    StageName: 'DeployManagedSolutionToACC'
#    dependsOn: 
#    - 'DeployManagedSolutionToQA'
##PREPROD
#- template: templates/DeploySolution.yml  # Template reference
#  parameters:
#    SolutionName: $(SolutionName)
#    PowerPlatformSPN: $(PowerPlatformSPN_PREPROD)
#    Environment: 'PREPROD-TDG'
#    StageName: 'DeployManagedSolutionToPREPROD'
#    dependsOn: 
#    - 'DeployManagedSolutionToQA'
##PROD
#- template: templates/DeploySolution.yml  # Template reference
#  parameters:
#    SolutionName: $(SolutionName)
#    PowerPlatformSPN: $(PowerPlatformSPN_PROD)
#    Environment: 'PROD-TDG'
#    StageName: 'DeployManagedSolutionToPROD'
#    dependsOn: 
#    - 'DeployManagedSolutionToQA'