trigger:
- none

pr:
- none

variables:
- name: SolutionExists
  value: true
- name: SolutionVersion
  value: ''
- name: SolutionDisplayName
  value: ''

- name: 'CoreLocalization'
  value: 'CoreLocalization'
  readonly: true
- name: 'TDG_NOP_Flows'
  value: 'TDG_NOP_Flows'
  readonly: true
- name: 'TC_CustomActions'
  value: 'TC_CustomActions'
  readonly: true
- name: 'TC_GlobalCore'
  value: 'TC_GlobalCore'
  readonly: true
- name: 'TDGConnectionReferences'
  value: 'TDGConnectionReferences'
  readonly: true
- name: 'TDGFlow'
  value: 'TDGFlow'
  readonly: true
- name: 'TDGFlowInspectionReport'
  value: 'TDGFlowInspectionReport'
  readonly: true
- name: 'TDGPlugins'
  value: 'TDGPlugins'
  readonly: true
- name: 'TDGTemplates'
  value: 'TDGTemplates'
  readonly: true

pool:
  vmImage: 'windows-latest'

steps:
- checkout: none
- task: MSCRMToolInstaller@12
  inputs:
    nugetFeed: 'official'
    psFeed: 'official'
- template: templates/stage/GetSolutionVersion.yml
  parameters:
    Solutions:
      - $(CoreLocalization)
      - $(TDG_NOP_Flows)
      - $(TC_CustomActions)
      - $(TC_GlobalCore)
      - $(TDGConnectionReferences)
      - $(TDGFlow)
      - $(TDGFlowInspectionReport)
      - $(TDGPlugins)
      - $(TDGTemplates)
    ConnectionString: $(ConnectionStringDev)
    EnvironmentName: 'DEV-TDG'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "${env:CORELOCALIZATION} Version: ${env:CORELOCALIZATIONVERSION}"
      Write-Host "${env:TDG_NOP_FLOWS} Version: ${env:FIELDSERVICEVERSION}"
      Write-Host "${env:TC_CUSTOMACTIONS} Version: ${env:TC_CUSTOMACTIONSVERSION}"
      Write-Host "${env:TC_GLOBALCORE} Version: ${env:TC_GLOBALCOREVERSION}"
      Write-Host "${env:TDGCONNECTIONREFERENCES} Version: ${env:TDGCONNECTIONREFERENCESVERSION}"
      Write-Host "${env:TDGFLOW} Version: ${env:TDGFLOWVERSION}"
      Write-Host "${env:TDGFLOWINSPECTIONREPORT} Version: ${env:TDGFLOWINSPECTIONREPORTVERSION}"
      Write-Host "${env:TDGPLUGINS} Version: ${env:TDGPLUGINSVERSION}"
      Write-Host "${env:TDGTEMPLATES} Version: ${env:TDGTEMPLATESVERSION}"
      Write-Host "SOLUTIONVERSION variable ${env:SOLUTIONVERSION}"