trigger:
- none

pr:
- none

variables:
- name: PowerPlatformSPN_COREDEV
  value: 'TDG CORE DEV'
- name: PowerPlatformSPN_Dev
  value: 'ROM DEV TDG'
- name: PowerPlatformSPN_QA
  value: 'ROM QA TDG'
- name: PowerPlatformSPN_COREQA
  value: 'TDG CORE QA'
- name: PowerPlatformSPN_ACC
  value: 'ROM ACC TDG'
- name: PowerPlatformSPN_ACCDATA
  value: 'ROM ACC TDG DATA'
- name: PowerPlatformSPN_PREPROD
  value: 'ROM PREPROD TDG'
- name: PowerPlatformSPN_PROD
  value: 'ROM PROD TDG'
- name: SolutionName
  value: 'TC_GlobalCore'

# # this is being defined in app-ci pipeline
# resources:
#   pipelines:
#   - pipeline: QM                                  # Name of the pipeline resource
#     source: Build - TDG Questionnaire Management  # Name of the pipeline referenced by the pipeline resource
#     trigger: 
#       branches:
#       - development
#   - pipeline: POWERAPPS_WEBRESOURCES              # Name of the pipeline resource
#     source: Build - TDG Webresources              # Name of the pipeline referenced by the pipeline resource
#     trigger: 
#       branches:
#       - development

stages:
- template: templates/stage/GetLatestSchemaPatchVersion.yml  # Template reference
  parameters:
    StageName: 'GetSchemaPatch'
    SolutionName: $(SolutionName)
    ConnectionString: $(ConnectionStringDev)
    PowerPlatformSPN: $(PowerPlatformSPN_DEV)
- template: templates/stage/DependencyCheck.yml  # Template reference
  parameters:
    SolutionName: '$(SolutionName)'
    ConnectionStringDest: '$(ConnectionStringDev)'
    ConnectionStringSource: '$(ConnectionStringDev)'
    StageName: 'DependencyCheck'
    dependsOn: 
    - 'GetSchemaPatch'