trigger:
- none

pr:
- none

name: 'Release Pipeline'

stages:
- stage: PrintPipelineVariables
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: PrintPipelineVariables
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "============================================"
          Write-Host "Echoing *Variable* Values"
          Write-Host "RevisionVersion:    $(RevisionVersion)"
          Write-Host "BuildPlatform:      $(BuildPlatform)"
          Write-Host "BuildConfiguration: $(BuildConfiguration)"
          Write-Host "MajorVersion:       $(MajorVersion)"
          Write-Host "MinorVersion:       $(MinorVersion)"
          Write-Host "PatchVersion:       $(PatchVersion)"
          Write-Host "SolutionName:       $(SolutionName)"
          Write-Host "PowerPlatformSPN:   $(PowerPlatformSPN)"
          Write-Host "============================================"
- template: templates/Template_CommitSolution.yml  # Template reference
  parameters:
    MajorVersion: $(MajorVersion)
    MinorVersion: $(MinorVersion)
    PatchVersion: $(PatchVersion)
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(Variables.PowerPlatformSPN)
- template: templates/Template_DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN)
- template: templates/Template_PatchSolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    ConnectionString: $(ConnectionStringDev)


