trigger:
- none

pr:
- none

variables:
  Version.Revision: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 0)]
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'
  MajorVersion: $(Pipeline_MajorVersion)
  MinorVersion: $(Pipeline_MinorVersion)
  PatchVersion: $(Pipeline_PatchVersion)
  SolutionName: $(Pipeline_SolutionName)
  PowerPlatformSPN: $(Pipeline_PowerPlatformSPN)

name: '$(Build.DefinitionName) $(MajorVersion).$(MinorVersion).$(PatchVersion).$(Date:yy)$(DayOfYear)$(Version.Revision)'

stages:
- template: templates/Template_CommitSolution.yml  # Template reference
  parameters:
    MajorVersion: $(MajorVersion)
    MinorVersion: $(MinorVersion)
    PatchVersion: $(PatchVersion)
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN)