trigger:
- none

pr:
- none

#variable 'Pipeline_ConnectionStringDev' defined in devops

variables:
  - name: PowerPlatformSPN_Dev
    value: 'ROM DEV TDG'
  - name: PowerPlatformSPN_QA
    value: 'ROM QA TDG'
  - name: PowerPlatformSPN_ACC
    value: 'ROM ACC TDG'
  - name: PowerPlatformSPN_ACCDATA
    value: 'ROM ACC TDG DATA'
  - name: PowerPlatformSPN_PREPROD
    value: 'ROM PREPROD TDG'
  - name: PowerPlatformSPN_PROD
    value: 'ROM PROD TDG'
  - name: SolutionName
    value: 'TC_CustomActions'
  - name: VersionMajor
    value: 1
  - name: VersionMinor
    value: 1
  - name: VersionPatch
    value: 0
  - name: StableVersionNumber
    value: '$(VersionMajor).$(VersionMinor).$(VersionPatch)'
  - name: VersionRevision
    value: $[counter(variables['StableVersionNumber'], 0)]
  - name: VersionNumber
    value: '$(StableVersionNumber).$(VersionRevision)'
  - name:  buildNumber
    value: ${{ format('{0}.{1}.{2}.{3}',  variables['VersionMajor'], variables['VersionMinor'], variables['VersionPatch'], variables['VersionRevision']) }}

name: #Set Dynamically in Pipeline

stages:
- stage: UpdateBuildNumber
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: UpdateBuildNumber
    steps:
    - task: PowerShell@2
      displayName: Set the name of the build (i.e. the Build.BuildNumber)
      inputs:
        targetType: 'inline'
        script: |
          [string] $buildName = "$(VersionNumber)"
          [string] $buildNumber = "$(buildNumber)"
          Write-Host "buildNumber = '$buildNumber'."
          Write-Host "Setting the name of the build to '$buildName'."
          Write-Host "##vso[build.updatebuildnumber]$buildName"
- stage: PrintPipelineVariables
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: PrintPipelineVariables
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'env | sort'
- template: templates/Template_UpdateBuildVersion.yml  # Template reference
  parameters:
    StageName: 'UpdateBuildVersion'
    VersionNumber: variables['VersionNumber']
    dependsOn: 
    - 'UpdateBuildNumber'
- template: templates/Template_CommitSolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_Dev)
    StageName: 'BuildAndPublishArtifacts'
    dependsOn: 
    - 'UpdateBuildVersion'
- template: templates/Template_DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_QA)
    Environment: 'QA'
    StageName: 'DeployManagedSolutionToQA'
    dependsOn: 
    - 'BuildAndPublishArtifacts'