trigger:
- none

pr:
- none

variables:
  - name: PowerPlatformSPN_Dev
    value: 'ROM DEV TDG'
  - name: PowerPlatformSPN_QA
    value: 'ROM QA TDG'
  - name: PowerPlatformSPN_ACC
    value: 'ROM ACC TDG'
  - name: PowerPlatformSPN_ACCDATA
    value: 'ROM ACC TDG DATA'
  - name: PowerPlatformSPN_PREPROD
    value: 'ROM PREPROD TDG'
  - name: PowerPlatformSPN_PROD
    value: 'ROM PROD TDG'
  - name: SolutionName
    value: 'TDGFlowInspectionReport'
  - name: VersionMajor
    value: 1
  - name: VersionMinor
    value: 1
  - name: VersionPatch
    value: 0
  - name: StableVersionNumber
    value: '$(VersionMajor).$(VersionMinor).$(VersionPatch)'
  - name: CounterVariable
    value: '$(SolutionName)_$(VersionMajor).$(VersionMinor).$(VersionPatch)'
  - name: VersionRevision
    value: $[counter(variables['CounterVariable'], 0)]
  - name: VersionNumber
    value: '$(StableVersionNumber).$(VersionRevision)'

name: #Set Dynamically in Pipeline

stages:
- stage: PrintPipelineVariables
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: PrintPipelineVariables
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'env | sort'
- template: templates/Template_UpdateBuildVersion.yml  # Template reference
  parameters:
    StageName: 'UpdateBuildVersion'
    VersionNumber: variables['VersionNumber']
- template: templates/Template_CommitSolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_Dev)
    StageName: 'BuildAndPublishArtifacts'
    dependsOn: 
    - 'UpdateBuildVersion'
#QA
- template: templates/Template_DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_QA)
    PowerPlatformSPN_Dev: $(PowerPlatformSPN_Dev) #used to update solution version after successful deployment to QA
    Environment: 'QA-TDG'
    StageName: 'DeployManagedSolutionToQA'
    DeleteSolution: false
    dependsOn: 
    - 'BuildAndPublishArtifacts'
#ACC
- template: templates/Template_DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_ACC)
    Environment: 'ACC-TDG'
    StageName: 'DeployManagedSolutionToACC'
    DeleteSolution: false
    dependsOn: 
    - 'DeployManagedSolutionToQA'
#PREPROD
- template: templates/Template_DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_PREPROD)
    Environment: 'PREPROD-TDG'
    StageName: 'DeployManagedSolutionToPREPROD'
    DeleteSolution: false
    dependsOn: 
    - 'DeployManagedSolutionToQA'
#PROD
- template: templates/Template_DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_PROD)
    Environment: 'PROD-TDG'
    StageName: 'DeployManagedSolutionToPROD'
    DeleteSolution: false
    dependsOn: 
    - 'DeployManagedSolutionToQA'