trigger: none
pr: none

#variable 'Pipeline_ConnectionStringDev' defined in devops

variables:
  - name: PowerPlatformSPN_Dev
    value: 'TDG CORE DEV'
  - name: PowerPlatformSPN_QA
    value: 'TDG CORE QA'
  - name: PowerPlatformSPN_ACC
    value: 'ROM ACC TDG'
  - name: PowerPlatformSPN_PREPROD
    value: 'ROM PREPROD TDG'
  - name: PowerPlatformSPN_PROD
    value: 'ROM PROD TDG'
  - name: SolutionName
    value: 'TDGRDCustomActions'
  - name: VersionMajor
    value: 1
  - name: VersionMinor
    value: 2
  - name: VersionPatch
    value: 0
  - name: StableVersionNumber
    value: '$(VersionMajor).$(VersionMinor).$(VersionPatch)'
  - name: CounterVariable
    value: $[format('{0}_{1}.{2}.{3}', variables['SolutionName'], variables['VersionMajor'], variables['VersionMinor'], variables['VersionPatch'])]
  - name: VersionRevision
    value: $[counter(variables['CounterVariable'], 1)]
  - name: VersionNumber
    value: '$(StableVersionNumber).$(VersionRevision)'

name: #Set Dynamically in Pipeline

stages:
- stage: UpdateBuildNumber
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: UpdateBuildNumber
    steps:
    - task: PowerShell@2
      displayName: Set the name of the build (i.e. the Build.BuildNumber)
      inputs:
        targetType: 'inline'
        script: |
          [string] $buildName = "$(VersionNumber)"
          Write-Host "Setting the name of the build to '$buildName'."
          Write-Host "##vso[build.updatebuildnumber]$buildName"
- stage: PrintPipelineVariables
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: PrintPipelineVariables
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'env | sort'
- template: templates/stage/UpdateBuildVersion.yml  # Template reference
  parameters:
    StageName: 'UpdateBuildVersion'
    VersionNumber: variables['VersionNumber']
    dependsOn: 
    - 'UpdateBuildNumber'
- template: templates/stage/CommitSolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_Dev)
    StageName: 'BuildAndPublishArtifacts'
    dependsOn: 
    - 'UpdateBuildVersion'
#QA
- template: templates/stage/DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_QA)
    PowerPlatformSPN_Dev: $(PowerPlatformSPN_Dev) #used to update solution version after successful deployment to QA
    Environment: 'QA-TDG'
    StageName: 'DeployManagedSolutionToQA'
    dependsOn: 
    - 'BuildAndPublishArtifacts'
#ACC
- template: templates/stage/DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_ACC)
    Environment: 'ACC-TDG'
    StageName: 'DeployManagedSolutionToACC'
    dependsOn: 
    - 'DeployManagedSolutionToQA'
#PREPROD
- template: templates/stage/DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_PREPROD)
    Environment: 'PREPROD-TDG'
    StageName: 'DeployManagedSolutionToPREPROD'
    dependsOn: 
    - 'DeployManagedSolutionToQA'
#PROD
- template: templates/stage/DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_PROD)
    Environment: 'PROD-TDG'
    StageName: 'DeployManagedSolutionToPROD'
    dependsOn: 
    - 'DeployManagedSolutionToQA'