trigger:
- none

pr:
- none

steps:
- checkout: self    
    
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "============================================"
      tree "$(Build.SourcesDirectory)" /F