trigger:
- none

pr:
- none

variables:
  - name: PowerPlatformSPN_Dev
    value: 'CID-DEV'
  - name: PowerPlatformSPN_QA
    value: 'CID-QA'
  - name: PowerPlatformSPN_ACC
    value: 'CID-ACC'
  - name: PowerPlatformSPN_PREPROD
    value: 'CID-PREPROD'
  - name: PowerPlatformSPN_PROD
    value: 'CID-PROD'
  - name: SolutionName
    value: 'CID_Flows'
  - name: VersionMajor
    value: 1
  - name: VersionMinor
    value: 0
  - name: VersionPatch
    value: 0
  - name: StableVersionNumber
    value: '$(VersionMajor).$(VersionMinor).$(VersionPatch)' #1.1.0
  - name: CounterVariable
    value: '$(SolutionName)_$(VersionMajor).$(VersionMinor).$(VersionPatch)' #CID_Flows_1.1.0
  - name: VersionRevision
    value: $[counter(variables['CounterVariable'], 0)] # unique count of string 'CID_Flows_1.1.0' globally in azure devops, starts at 0
  - name: VersionNumber
    value: '$(StableVersionNumber).$(VersionRevision)' #1.1.0.0

name: #Set Dynamically in Pipeline

stages:
- stage: PrintPipelineVariables # shows all pipeline variables
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: PrintPipelineVariables
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'env | sort'
- template: templates/stage/UpdateBuildVersion.yml  # Template reference
  parameters:
    StageName: 'UpdateBuildVersion'
    VersionNumber: variables['VersionNumber']
- template: templates/stage/CommitSolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_Dev)
    StageName: 'BuildAndPublishArtifacts'
    dependsOn: 
    - 'UpdateBuildVersion'
   # addFilesToArtifact:
   #- '$(Build.SourcesDirectory)\Pipelines\ROM\connection_references\CIDFlows_SolutionSettings_QA.json'
   # - '$(Build.SourcesDirectory)\Pipelines\ROM\connection_references\CIDFlows_SolutionSettings_ACC.json'
   # - '$(Build.SourcesDirectory)\Pipelines\ROM\connection_references\CIDFlows_SolutionSettings_PREPROD.json'
   # - '$(Build.SourcesDirectory)\Pipelines\ROM\connection_references\CIDFlows_SolutionSettings_PROD.json'
    

#QA
- template: templates/stage/DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_QA)
    PowerPlatformSPN_Dev: $(PowerPlatformSPN_Dev) #used to update solution version after successful deployment to QA
    #UseDeploymentSettingsFile: true
    #DeploymentSettingsFile: 'CIDFlows_SolutionSettings_QA.json'
    Environment: 'QA-TDG'
    StageName: 'DeployManagedSolutionToQA'
    DeleteSolution: false
    dependsOn: 
    - 'BuildAndPublishArtifacts'
#ACC
- template: templates/stage/DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_ACC)
    #UseDeploymentSettingsFile: true
    #DeploymentSettingsFile: 'CIDFlows_SolutionSettings_ACC.json'
    Environment: 'ACC-TDG'
    StageName: 'DeployManagedSolutionToACC'
    DeleteSolution: false
    dependsOn: 
    - 'DeployManagedSolutionToQA'
#PREPROD
- template: templates/stage/DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_PREPROD)
    #UseDeploymentSettingsFile: true
    #DeploymentSettingsFile: 'CIDFlows_SolutionSettings_PREPROD.json'
    Environment: 'PREPROD-TDG'
    StageName: 'DeployManagedSolutionToPREPROD'
    DeleteSolution: false
    dependsOn: 
    - 'DeployManagedSolutionToQA'
#PROD
- template: templates/stage/DeploySolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    PowerPlatformSPN: $(PowerPlatformSPN_PROD)
    #UseDeploymentSettingsFile: true
    #DeploymentSettingsFile: 'CIDFlows_SolutionSettings_PROD.json'
    Environment: 'PROD-TDG'
    StageName: 'DeployManagedSolutionToPROD'
    DeleteSolution: false
    dependsOn: 
    - 'DeployManagedSolutionToQA'

