trigger:
- none

pr:
- none

#variable 'Pipeline_ConnectionStringDev' defined in devops

variables:
  - name: SolutionName
    value: 'TC_GlobalCore'

stages:
- template: templates/stage/PatchSolution.yml  # Template reference
  parameters:
    SolutionName: $(SolutionName)
    ConnectionString: $(Pipeline_ConnectionStringDev)
    StageName: 'CreatePatchOnDev'