adx_append: false
adx_appendto: false
adx_create: false
adx_delete: false
adx_entitylogicalname: qm_environmentsettings
adx_entityname: EnvironmentSetting
adx_entitypermission_webrole:
- 844598bc-d0cb-410a-b2de-b6f2c4dbc487
- 42faa683-93a4-ec11-b3fe-0022483c4a6f
adx_entitypermissionid: 8ce7870c-4c72-ec11-8942-000d3a840e6b
adx_read: true
adx_scope: 756150000
adx_write: false
