adx_sitesetting:
  - adx_name: Authentication/OpenIdConnect/OpenId_1/ClientId
    adx_sitesettingid: e8c82f77-0959-ec11-8f8e-0022483c409d
    adx_value: {{QAAuthID}}
  - adx_name: Authentication/OpenIdConnect/OpenId_1/RedirectUri
    adx_sitesettingid: e6c82f77-0959-ec11-8f8e-0022483c409d
    adx_value: https://tdgcore-qa.powerappsportals.com/signin-openid_1
  - adx_name: Authentication/OpenIdConnect/OpenId_1/ClientSecret
    adx_sitesettingid: ebc82f77-0959-ec11-8f8e-0022483c409d
    adx_value: {{QAAuthSecret}}
