parameters:
  - name: SolutionName
    type: string
  - name: ConnectionStringDest
    type: string
  - name: ConnectionStringSource
    type: string
  - name: StageName
    type: string
  - name: dependsOn
    type: object
    default: []
    
stages:
- stage: ${{Parameters.StageName}}
  dependsOn:
  - ${{ each stage in parameters.dependsOn }}:
    - ${{ stage }}
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: ${{Parameters.StageName}}_Job
    steps:
    - checkout: none
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "============================================"
          Write-Host "Echoing Parameter Values"
          Write-Host "Parameters.SolutionName: ${{Parameters.SolutionName}}"
          Write-Host "Parameters.StageName: ${{Parameters.StageName}}"
          Write-Host "============================================"
    - task: MSCRMToolInstaller@12
      displayName: Power DevOps Tool Installer

    - task: MSCRMGetSolutionMissingComponents@12
      inputs:
        crmConnectionString: '${{Parameters.ConnectionStringDest}}'
        solutionFile: '$(Build.ArtifactStagingDirectory)\zip\${{Parameters.SolutionName}}_Managed.zip'
        errorIfMissing: true
        crmConnectionTimeout: '999'

#    - task: MSCRMGetSolutionMissingDependencies@12
#      inputs:
#        crmConnectionString: '${{Parameters.ConnectionStringSource}}'
#        solutionName: ${{Parameters.SolutionName}}
#        warnIfMissing: true