parameters:
  - name: StageName
    type: string
  - name: VersionNumber
    type: string
  - name: dependsOn
    type: object
    default: []
    
stages:
- stage: ${{Parameters.StageName}}
  dependsOn:
  - ${{ each stage in parameters.dependsOn }}:
    - ${{ stage }}
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: ${{Parameters.StageName}}
    steps:
      - checkout: none
      - task: PowerShell@2
        displayName: Set the name of the build to next solution version
        inputs:
          targetType: 'inline'
          script: |
            [string] $buildName = ${env:PATCHVERSION}
            Write-Host "Setting the name of the build to '$buildName'."
            Write-Host "##vso[build.updatebuildnumber]$buildName"